[package]
name = "ndn-operator"
version = "0.1.0"
edition = "2024"

[lib]
name = "controller"
path = "src/lib.rs"

[[bin]]
name = "gencrd"
path = "src/bin/gencrd.rs"

[[bin]]
name = "genconfig"
path = "src/bin/pod_init.rs"

[dependencies]
actix-web = "4.9.0"
anyhow = "1.0.96"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5.34", features = ["derive"] }
futures = "0.3.31"
k8s-openapi = { version = "0.24.0", features = ["latest"] }
kube = { version = "0.99.0", features = ["runtime", "client", "derive"] }
schemars = "0.8.22"
serde = "1.0.218"
serde_json = "1.0.139"
serde_with = "3.12.0"
serde_yaml = "0.9.34"
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["json", "env-filter"] }
