apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndn-operator
rules:
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["named-data.net"]
  resources: ["networks", "routers"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: ["named-data.net"]
  resources: ["networks/status", "routers/status"]
  verbs: ["update", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "patch", "delete"]
