apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ndn-operator
subjects:
- kind: ServiceAccount
  name: ndn-operator
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ndn-operator
  apiGroup: rbac.authorization.k8s.io