apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ndn-controller-{{ .Release.Name }}
  namepace: {{ .Release.Namespace }}
  labels:
    named-data.net/component: ndn-controller
    named-data.net/instance: {{ .Release.Name }}
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["create", "patch", "delete"]