apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndn-controller-{{ .Release.Name }}
  labels:
    named-data.net/component: ndn-controller
    named-data.net/instance: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: ["named-data.net"]
  resources: ["networks"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: ["named-data.net"]
  resources: ["routers"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: ["named-data.net"]
  resources: ["networks/status", "routers/status"]
  verbs: ["update", "patch"]
- apiGroups: ["events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "patch"]
