apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndn-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndn-operator
  template:
    metadata:
      labels:
        app: ndn-operator
    spec:
      serviceAccountName: ndn-operator
      containers:
        - name: ndn-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"