apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndn-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: ndn-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndn-operator
  template:
    metadata:
      labels:
        app: ndn-operator
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      serviceAccountName: ndn-operator
      containers:
        - name: ndn-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
          - name: RUST_LOG
            value: "{{ .Values.logLevel }}"
          resources:
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"