apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ndn-inject-{{ .Release.Name }}
  labels:
    named-data.net/component: ndn-inject
    named-data.net/instance: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "patch"]
- apiGroups: ["named-data.net"]
  resources: ["networks"]
  verbs: ["get", "list"]
- apiGroups: ["named-data.net"]
  resources: ["routers"]
  verbs: ["get", "list"]


