apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndn-injector
  namespace: {{ .Release.Namespace }}
  labels:
    named-data.net/component: ndn-injector
    named-data.net/instance: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
