{{- $host := printf "ndn-inject.%s.svc" .Release.Namespace }}
{{- $ca := genSelfSignedCert $host (list) (list $host) 365 }}
kind: Secret
apiVersion: v1
metadata:
  name: ndn-inject-tls
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ ternary (b64enc (trim $ca.Cert)) (b64enc (trim .Values.injector.tls.crtPEM)) (empty .Values.injector.tls.crtPEM) }}
  tls.key: {{ ternary (b64enc (trim $ca.Key)) (b64enc (trim .Values.injector.tls.keyPEM)) (empty .Values.injector.tls.keyPEM) }}