apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ndn-operator
  name: ndn-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["named-data.net"]
  resources: ["networks"]
  verbs: ["get", "watch", "list", "update", "patch"]
- apiGroups: ["named-data.net"]
  resources: ["networks/status"]
  verbs: ["update", "patch"]