apiVersion: v1
kind: ServiceAccount
metadata:
  name: ndn-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: ndn-operator
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
